src/App.js
src/constants/states.js
src/index.js

States Added

---

.travis.yml
README.md
package.json
src/__tests__/App.test.js
src/utils/__tests__/formatNumber.test.js
src/utils/__tests__/formatPercent.js
src/utils/formatPercent.js
yarn.lock

- Tests added
- Travis and coveralls setup
> Part of #13 

tests and travis coveralls added

---

src/components/MainPage/MainPage.js

- Copy adjusted in accordance with mocks.
> Closes #9.

Removed article and added calculated dates

---

src/components/shared/Card/Card.js
src/components/shared/Card/Card.scss

- Added alt text and tabIndex to the hint button
> Closes #11.

Card hint made accessible

---

src/components/MainPage/MainPage.js
src/components/shared/ErrorBoundary/ErrorBoundary.js
src/components/shared/ErrorBoundary/ErrorBoundary.scss
src/components/shared/ErrorBoundary/__tests__/ErrorBoundary.test.js
src/components/shared/ErrorBoundary/index.js

- Error boundaries added for all major components
> Closes #10.

Error boundaries added

---

src/components/Chart/Chart.js
src/components/FlowDiagram/FlowDiagram.scss
src/components/shared/Card/Card.scss

- changed brand colors
> Closes #26.

changed colors

---

src/components/Chart/Chart.js

- Added vertical line (Chart component).
- Tooltips united to show data for the whole period.
> Closes #25.

added vertical line and formatted tooltips

---

package.json
src/App.js
src/assets/scss/_variables.scss
src/components/FlowDiagram/Arrow.js
src/components/FlowDiagram/Arrow.scss
src/components/FlowDiagram/FlowDiagram.js
src/components/FlowDiagram/FlowDiagram.scss
src/components/FlowDiagram/__tests__/FlowDiagram.test.js
src/components/KeyInsights/KeyInsights.js
src/components/KeyInsights/KeyInsights.scss
src/components/KeyInsights/index.js
src/components/KeyInsights/propTypes.js
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.scss
src/components/MainPage/__tests__/MainPage.test.js
src/components/shared/Card/Card.js
src/components/shared/Card/Card.scss
src/components/shared/Card/__tests__/Card.test.js
src/components/shared/ErrorBoundary/__tests__/ErrorBoundary.test.js
src/constants/metrics.js
src/data.json
src/utils/__tests__/generateFlowDiagramData.js
src/utils/generateFlowDiagramData.js
src/utils/generateKeyInsightsData.js
yarn.lock

- Added Key Insights connected to mock data.
- Fixed mobile UI according to mocks.
- Changed metric names according to PRD.
> Closes #27.
Closes #14.

Key insights section and flow diagram mobile

---

src/components/Chart/Chart.js
src/components/Chart/Chart.scss
src/components/Chart/utils/adjustChartDataLength.js
src/data.json

- Added new state (not available) to chart component. 
> Closes #33.

added not available state to chart

---

src/components/Chart/Chart.js

- Added line connecting for missing data points.
> Closes #46.
> Closes #47.

added chart line connect

---

package.json
src/App.js
src/utils/__tests__/generateChartData.test.js
src/utils/generateChartData.js
src/utils/generateSourceData.js
yarn.lock

- Source info from charts data now used to create source text at the bottom section.
> Closes #31.

Сharts source data usage

---

src/components/Chart/Chart.js
src/components/Chart/PeriodPicker.js
src/components/Chart/__tests__/Chart.test.js
src/components/Chart/__tests__/PeriodPicker.test.js

- Added buffer month
- Fixed bug when All time months count equal to 1 years or 5 years months count.
> Closes #54.

added buffer month and fixed bug

---

package.json
src/App.js
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.scss
yarn.lock

- Added the case when no data for a given state is available
> Closes #60.

No state data case

---

src/components/KeyInsights/KeyInsights.js
src/components/Sources/Source.js
src/components/shared/Card/Card.js
src/components/shared/Card/Card.scss
src/utils/generateKeyInsightsData.js

- No change cases for key insights section.
- Typo fixes
- accessibility fixes
> Closes #52.

added no change cases

---

src/components/Chart/Chart.js
src/components/Chart/Chart.scss
src/components/Chart/__tests__/Chart.test.js
src/components/Chart/utils/calcMetricPercentage.js
src/components/Sources/Source.js
src/utils/generateChartData.js

Adjustments on:
- chart tooltips
- chart `not available` state
- case when metric has only one data point 
- "0%" and "+0%" issue
- thousand separators
> Closes #53.

Chart adjustments (#53).

---

src/App.js
src/components/Jails/Jails.js
src/components/MainPage/MainPage.js
src/components/shared/Sources/Sources.js

Added sources section for the new Jails view
Closes #43 

Support the sources section at the bottom of the Jails view

---

src/App.js
src/components/FlowDiagram/FlowDiagram.scss
src/components/MainPage/MainPage.js
src/components/shared/Card/Card.scss
src/constants/metrics.js
src/utils/formatNumber.js

1. Added small copy changes
2. Fixed visual design bugs
> Closes #66 , Closes #68 

Fixes visual design bugs & copy changes

---

src/App.js
src/components/FlowDiagram/Arrow.scss
src/components/FlowDiagram/FlowDiagram.js
src/components/FlowDiagram/FlowDiagram.scss
src/components/MainPage/MainPage.js
src/components/shared/Card/Card.js
src/components/shared/Card/Card.scss
src/constants/metrics.js
src/utils/__tests__/generateHint.test.js
src/utils/formatNumber.js
src/utils/generateFlowDiagramData.js
src/utils/generateHint.js

Added the date range to each metric block
> Closes #70 

Date range to each metric block

---

src/App.js
src/components/shared/Card/Card.js
src/components/shared/Card/Card.scss
src/components/shared/Card/__tests__/Card.test.js
src/utils/generateFlowDiagramData.js

Converged "Data Not Available" Behavior
> Closes #81 

Converge "Data Not Available" behavior

---

src/App.js
src/components/Jails/CountySelector/County.js
src/components/Jails/CountySelector/County.scss
src/components/Jails/CountySelector/CountySelector.js
src/components/Jails/CountySelector/CountySelector.scss
src/components/Jails/CountySelector/__tests__/County.test.js
src/components/MainPage/MainPage.scss
src/utils/__tests__/getNormalizedCountyData.test.js
src/utils/getNormalizedCountyData.js

Prevent selecting a county that does not have data in county selector. 
Closes #85 

Prevent selecting a county that does not have data in county selector

---

src/App.js

Added new lines to the "Releases" graph.
> Closes #87 

Add new lines to the "Releases" graph

---

src/App.js
src/components/Jails/CountySelector/CountySelector.js
src/components/Jails/Jails.js
src/components/MainPage/MainPage.js
src/components/shared/Chart/Chart.js
src/components/shared/Sources/Sources.js

1. Added various copy tweaks
2. Changed the logic for the default county in the Jails Incarceration Rate graph
3. Added the "% counties reporting" to the Statewide Incarceration Rate tooltip
> Closes #97 , closes #98 , closes #99 

Jails improvements

---

src/App.js
src/components/MainPage/MainPage.js
src/components/shared/Card/Card.js
src/utils/__tests__/getLastUpdatedDate.test.js
src/utils/generateFlowDiagramData.js
src/utils/generateJailsKeyInsightsData.js
src/utils/getLastUpdatedDate.js

> Added the Last Updated date to the header
> Closes #101 

Add the Last Updated date to the header

---

src/components/MainPage/MainPage.js

Updated the copy for the slider more accurate and helpful
> Closes #111 

Update the copy for the slider more accurate and helpful

---

src/components/MainPage/MainPage.js
src/components/Sources/Sources.js
src/components/Sources/Sources.scss
src/components/Sources/__tests__/Sources.test.js
src/components/shared/Card/Card.js
src/utils/formatDatePeriod.js
src/utils/generateCorrectionsKeyInsightsData.js
src/utils/generateJailsKeyInsightsData.js
src/utils/getKeyInsightsCaptionFragment.js

This incorporates the copy changes requested by CSG from the last two emails that they sent.
> Closes [#XXXX]

Round of copy changes

---

src/App.js
src/constants/metrics.js

Changes all copy references from "commitments" to "admissions" everywhere in the app.
Closes #129 

Changes copy references from commitments to admissions.

---

src/components/MainPage/MainPage.js

Going ahead and making this change so that it is in the version that CSG copy edits.
Closes #127 

Modify switch copy as monthly data is not shown on annual

---

README.md

We were fairly out-of-date, but this gets us back up-to-speed! 🏎️ 
Closes #92 

Updates the section in the README describing the input data specification

---

src/components/Jails/Jails.js
src/components/Jails/ReportingCounties/ReportingCounties.js
src/components/Jails/ReportingCounties/ReportingCounties.scss
src/components/MainPage/MainPage.js
src/components/MainPage/MainPage.scss
src/index.js
src/utils/generateCorrectionsKeyInsightsData.js

This takes care of the last set of copy changes that CSG sent over!
N/A

Final copy edits from CSG

---

src/App.js
src/components/Jails/CountySelector/CountySelector.js
src/components/MainPage/MainPage.js
src/components/Sources/Sources.js
src/utils/getAdditionalDescription.js

A series of copy changes requested in final pre-launch QA.
Closes #143 

Applies final copy changes requested by CSG.
